config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'
  
  resources :users
  resources :artists 
  resources :cities, except: [:delete]
  resources :events, except: [:delete]
  resources :utilities
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'

  get '/search_artist', to: 'artists#new'
  get '/search_artist/:id', to: 'artist#create'
  post '/search', to: 'artists#search'
  get '/search', to: 'artists#search'
  get '/add_artist', to: 'artists#create'
  
  get '/update_cal', to: 'utilities#edit'
  
  
end

app/views/shared/_cal_list.html.erb
<! Requires 'events' >
<% if events.count != 0 %>
	<div class="calendar">
		<h2>Legend:</br> *  Cleveland, ~ London, v Sydney, < Los Angeles</h2>
		<div class="cal_break">
			<h1><%= @year = Date.today.year %></h1>
			<h2><% @month = Date.today.month %><%= Date.today.strftime('%B') %></h2>
		</div>				
		<div>
				<% @date_range.each do |date| %>
					<% if date != @date %>
						<break/>
						<% @date = date %>
						</div>
						<% if @date.year != @year %>
						    <div class="cal_break">
							    <h1><%= @year = @date.year %></h1>
							    <h2><% @month = @date.month %><%= @date.strftime('%B') %></h2>
							</div>
						<% elsif @date.month != @month %>
						    <div class="cal_break">
						        <h2><% @month = @date.month %><%= @date.strftime('%B') %></h2>
						    </div>
						<% end %>
						<% if @corelated_events.select{|event| event[:date] == @date}.count > 0 %>
							<div class="date" id="multiple">
						<% else %>
							<div class="date">
								
						<% end %>
						<table>
	    					<tr>
	    						<th><%= @date.mday %></th>
	    					</tr>
	    				</table>
					<% end %>
					<ul class="count">
						<li onclick=""><%=	(@local = events.where(play_date: @date)).count %>
						<%= near_shop(@local) %>
							<ul class="events">
								<% events.where(play_date: @date).each do |event| %>
								<% if event.artist.client_status == "Current" %>
						            <li class="current">
						        <% elsif event.artist.client_status == "Prospective" %>
						            <li class="prospective">
						        <% else %>
						            <li class="former">
						        <% end %>
									<% @artist_name = event.artist_name + shop_marker(event.Region) %>
									<%= link_to(@artist_name, event_path(event)) %></li>
									
								<% end %>
								<hr>
								<% @corelated_events.select{|event| event[:date] == @date}.each do |city|%>
									<li><%= link_to(city[:region], city_path(city[:region_id], :date => @date)) %></li>
								<% end %>
							</ul>
						</li>
					</ul>
				<% end %>
			    
		</div>
	</div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
      <h5>Please correct the following errors: </h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>
  

app/views/shared/_event_list.html.erb
<! Requires 'events' >
<% if events.count != 0 %>
	<div class="calendar">
		<div class="cal_break">
			<h1><%= @year = events.first.play_date.to_date.year %></h1>
		</div>				
		<table>
			<% events.each do |event| %>
				<% if event.play_date.to_date != @date %>							
					<% @date = event.play_date.to_date %>	
					<% if @date.year != @year %>
						</table>
						<div class="cal_break">
						    <h1><%= @year = @date.year %></h1>
						</div>
						<table>
					<% end %>
					<tr>
						<th colspan="4"><%= @date.month %>/<%= @date.mday %></th>
					</tr>
				<% end %>
				<tr>
					<td><%= link_to(event.artist_name, artist_path(event.artist)) %></td>
					<td><%= link_to(event.VenueName, event_path(event)) %></td>
					<td><%= link_to(event.Region, city_path(event.city)) %></td>					
				</tr>	
			<% end %>
		</table>
	</div>
<% end %>

app/views/shared/_page_title.html.erb
<p>
  <h1><%= title %></h1>
  <hr/>
</p>

app/views/shared/_page_title_html.erb
<p>
  <h1><%= title %></h1>
  <hr/>
</p>