config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'
  
  resources :users
  resources :artists 
  resources :cities, except: [:delete]
  resources :events, except: [:delete]
  resources :utilities
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'

  get '/search_artist', to: 'artists#new'
  get '/search_artist/:id', to: 'artist#create'
  post '/search', to: 'artists#search'
  get '/search', to: 'artists#search'
  get '/add_artist', to: 'artists#create'
  
  get '/update_cal', to: 'utilities#edit'
  
  
end

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Client Tracker</h1>
  
  <h2>
   <p>When you need to know, you just need to know.  
       No pretty pictures, no advertising, just pure data.</p> 
   <p>Client Tracker is a web based company wide application which acquires and organizes data from Pollstar.com.</p>
   <p>Need to ship something to a client?  
        Use Client Trackers artist index to find their next venue.</p>  
   <p>Going to visit a client?  
        Select the venue from their itinerary and see if any of your other clients are nearby.</p>
   <p>Want to know which clients are coming through town?
        Use the city list to find out who is playing in your city.</p> 
   <p>These are the current features built into Client Tracker.  There are many more yet to come.</p>
   <p>Features such as Crew Track, which will be able to send an automated email to your tour staff letting them know
         who they are touring with, contact info for touring staff, production details, and a rough tour schedule.</p>
   <p>Built in FedEx features.  Select the artist event you need to ship to and hit the FedEx button, fill in a few 
         details about the package and it will fill out the shipping info.  If you are using Crew Track, 
         it could even fill in the crew chief name and details.</p>
  </h2>
  
  <!--<%= link_to "Sign up now!", register_path, class: "btn btn-lg btn-success" %>-->
</div>