config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'
  
  resources :users
  resources :artists 
  resources :cities, except: [:delete]
  resources :events, except: [:delete]
  resources :utilities
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'

  get '/search_artist', to: 'artists#new'
  get '/search_artist/:id', to: 'artist#create'
  post '/search', to: 'artists#search'
  get '/search', to: 'artists#search'
  get '/add_artist', to: 'artists#create'
  
  get '/update_cal', to: 'utilities#edit'
  
  
end

app/views/layouts/_footer.html.erb
  <div class="footer">
    <p>Data by: Pollstar.com</p>
  	<p>Last updated: <%= last_updated %> </p>
    <p>&copy; Client Tracker 2015</p>
  </div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss-"alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
  <header class="navbar navbar-fixed-top navbar-default" id="nav">
    <div class="container">
      <div class="nav_item">
        <a href="http://www.8thdaysound.com">
          <%= image_tag("logo.jpg", width: 180, height: 105) %>
        </a>
      </div>
      <div class="nav_item">
        <%= link_to "Client Tracker", "", class: "btn btn-lg btn-success", id: "logo" %>
      </div>
        <div class="sub_menu">
           <ul class="sub_menu">
             <li><%= link_to("Main Calendar",events_path) %></li>
             <li><%= link_to("Artist List", artists_path) %></li>
             <li><%= link_to("City List", cities_path) %></li>
             <li><%= link_to("Search for Artist", search_artist_path) %></li>
             <!--<li><%= link_to("User List", users_path) %></li>-->
             <li><%= link_to("Utilities", utilities_path ) %></li>
           </ul>
        </div>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%= favicon_link_tag 'logo.jpg' %>
	  <title>Client Tracker</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div>
			<%= render 'layouts/navigation' %>
		</div>
		<div class="container">
			<%= render 'layouts/messages' %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div> 
	</body>
</html>